### ISSUE TITLE
Is this lib SSR compatible?

### ISSUE THREAD

**Issue by mthompson** [Download/preact-layout#18]
Hi,

I've just recently came across you layout lib.

I'm looking to incorporate this into a SSR solution using Preact + [Razzle](https://github.com/jaredpalmer/razzle/tree/master/examples/with-preact).

Have you have had success integrating this lib with the latest Preact  +  SSR approach?

Thanks in advance for any advice / examples that you can afford me at this time.

**Comment by Download** [comment]
I think this lib is hopelessly out of date. You would need to port to the latest version of Preact first. It was a bit of an experiment. But it did work reasonably well. I just never found the time to maintain it.

**Comment by Download** [comment]
Oh but to answer the question: Yes, it should be SSR compatible.

**Comment by mthompson** [comment]
Thanks for confirming.

**Comment by mthompson** [comment]
closing...
